#--- Hyper-parameters for the XOR experiment ---#

[NEAT]
fitness_criterion     = max
fitness_threshold     = 100.0
pop_size              = 150
reset_on_extinction   = False

[ExHebbGenome]
# node activation options
activation_default      = tanh
activation_mutate_rate  = 0.01
activation_options      = tanh

# node aggregation options
aggregation_default     = sum
aggregation_mutate_rate = 0.0
aggregation_options     = sum

# node bias options
bias_init_mean          = 0.0
bias_init_stdev         = 1.0
bias_max_value          = 30.0
bias_min_value          = -30.0
bias_mutate_power       = 0.5
bias_mutate_rate        = 0.7
bias_replace_rate       = 0.1

# genome compatibility options
compatibility_disjoint_coefficient = 1.0
compatibility_weight_coefficient   = 0.5
compatibility_global_param_coefficient = 0.25

# connection add/remove rates
conn_add_prob           = 0.5
conn_delete_prob        = 0.5

# connection enable options
enabled_default         = True
enabled_mutate_rate     = 0.01

feed_forward            = False
initial_connection      = full_direct

# node add/remove rates
node_add_prob           = 0.2
node_delete_prob        = 0.2

# network parameters
num_hidden              = 0
num_inputs              = 2
num_outputs             = 1

# node response options
response_init_mean      = 1.0
response_init_stdev     = 0.0
response_max_value      = 30.0
response_min_value      = -30.0
response_mutate_power   = 0.0
response_mutate_rate    = 0.0
response_replace_rate   = 0.0

# connection weight options
weight_init_mean        = 0.0
weight_init_stdev       = 1.0
weight_max_value        = 30
weight_min_value        = -30
weight_mutate_power     = 0.5
weight_mutate_rate      = 0.8
weight_replace_rate     = 0.1

# exhebb param options
a_replace_rate          = 0.01
b_replace_rate          = 0.01
c_replace_rate          = 0.01
d_replace_rate          = 0.01
eta_replace_rate          = 0.01
m_d_replace_rate          = 0.0

a_mutate_rate           = 0.01
b_mutate_rate           = 0.01
c_mutate_rate           = 0.01
d_mutate_rate           = 0.01
eta_mutate_rate           = 0.01
m_d_mutate_rate           = 0.0

a_max_value             = 30
b_max_value             = 30
c_max_value             = 30
d_max_value             = 30
eta_max_value             = 30
m_d_max_value             = 0

a_min_value             = -30
b_min_value             = -30
c_min_value             = -30
d_min_value             = -30
eta_min_value             = -30
m_d_min_value             = 0

a_mutate_power          = 0.5
b_mutate_power          = 0.5
c_mutate_power          = 0.5
d_mutate_power          = 0.5
eta_mutate_power          = 0.5
m_d_mutate_power          = 0

[DefaultSpeciesSet]
compatibility_threshold = 4.0

[DefaultStagnation]
species_fitness_func = max
max_stagnation       = 20
species_elitism      = 2

[DefaultReproduction]
elitism            = 2
survival_threshold = 0.2
min_species_size   = 32 
