name: Action ci

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  example-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install package dependencies
        run: sudo apt install -y graphviz
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Run Default
        run: python ./myexamples/example.py --generation 10 --task task.xor 
      - name: Run HebbFFN
        run: python ./myexamples/example.py --network HebbFFN --generation 10
      - name: Run IndExHebbFFN
        run: python ./myexamples/example.py --network IndExHebbFFN --config ./myexamples/configs/indexhebb_genome.ini --generation 10
      - name: Run ModHebbFFN
        run: python ./myexamples/example.py --network ModHebbFFN --config ./myexamples/configs/mod_genome.ini --generation 10
      - name: Run ModIndExHebbFFN
        run: python ./myexamples/example.py --network ModIndExHebbFFN --config ./myexamples/configs/modindexhebb_genome --generation 10
