name: dev CI

on:
  push:
    branches: 
      - develop/ci

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install package dependencies
        run: sudo apt update && sudo apt install -y graphviz
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install modneat
        run: pip install .

      - name: Run testcase 01
        run: python -m modneat.run --task xor --config ./configs/bool_global.ini
        working_directory: ./tests
        continue-on-error: true

      - name: Run testcase 02
        run: python -m modneat.run --task xor --config ./configs/float_local.ini
        working_directory: ./tests
        continue-on-error: true

      - name: Run testcase 03 (Multi-Core)
        run: python -m modneat.run --task xor --config ./configs/float_local.ini --num_workers 2
        working_directory: ./tests
        continue-on-error: true